version: 2
jobs:
  build:
    docker:
      - image: clojure:temurin-23-lein-noble

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Bring down deps
          command: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Install Planck
          command: |
            apt-get update
            apt-get install -y software-properties-common

            # There are no recent planck binaries, so bring in necessary support from older ubuntu versions
            add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu focal main universe"
            add-apt-repository -y "deb http://security.ubuntu.com/ubuntu focal-security main"

            # not automatically installed by planck, but needed by planck, so compensate
            DEBIAN_FRONTEND=noninteractive apt-get install -y libicu66 libjavascriptcoregtk-4.0-18

            wget https://launchpad.net/~mfikes/+archive/ubuntu/planck/+files/planck_2.25.0-1ppa1~focal1_amd64.deb
            apt-get install ./planck_2.25.0-1ppa1~focal1_amd64.deb

      - run:
          name: Tools Versions
          command: |
            echo lein --version
            lein --version
            echo java -version
            java -version
            echo planck --version
            planck --version

      - run:
          name: Test
          command: lein test-all
